function sigDEN = func_denoise_dw1d(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 23-May-2023 15:23:57

% Analysis parameters.
%---------------------
wname = 'db6';
level = 6;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = sln;
sorh = 's';    % Specified soft or hard thresholding
thrSettings = 53.036712757200569;

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
